### ISSUE TITLE
`NoSuchMethodError: ApplicationLoader.initConfigurationStore` when attempting to update platform to `241.15989.69`

### ISSUE THREAD

**Issue by xuansontrinh** [JetBrains/intellij-platform-gradle-plugin#1607]
### What happened?

our team is using Gradle plugin `1.17.2` to build our project and we encountered the issue of `NoSuchMethodError: ApplicationLoader.initConfigurationStore` after attempting to update the platform version to `241.15989.69`.

### Relevant log output or stack trace

```shell
java.lang.NoSuchMethodError: 'java.lang.Object com.intellij.platform.ide.bootstrap.ApplicationLoader.initConfigurationStore(com.intellij.openapi.application.impl.ApplicationImpl, kotlin.coroutines.Continuation)'
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invokeSuspend(testApplication.kt:167)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invokeSuspend(testApplication.kt:177)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invoke(testApplication.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.platform.util.progress.ProgressPipeImpl.collectProgressUpdates(ProgressPipe.kt:41)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2$taskJob$1.invokeSuspend(PlatformTaskSupport.kt:138)
        at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2$taskJob$1.invokeSuspend(PlatformTaskSupport.kt:138)
      Caused by: java.lang.NoSuchMethodError: 'java.lang.Object com.intellij.platform.ide.bootstrap.ApplicationLoader.initConfigurationStore(com.intellij.openapi.application.impl.ApplicationImpl, kotlin.coroutines.Continuation)'
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invokeSuspend(testApplication.kt:167)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invokeSuspend(testApplication.kt:177)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invoke(testApplication.kt)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invoke(testApplication.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.platform.util.progress.ProgressPipeImpl.collectProgressUpdates(ProgressPipe.kt:41)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2$taskJob$1.invokeSuspend(PlatformTaskSupport.kt:138)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Steps to reproduce

Check out this branch: https://github.com/JetBrains/intellij-bazel/tree/son/new_eap

### Gradle IntelliJ Plugin version

1.17.2

### Gradle version

8.7

### Operating System

macOS

**Comment by xuansontrinh** [comment]
seems like this behaviour is flaky.
It becomes not-reproducible for me for now so I will close this issue.

**Comment by xuansontrinh** [comment]
seems like this behaviour is flaky.
It becomes not-reproducible for me for now so I will close this issue.
