### ISSUE TITLE
Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'

### ISSUE THREAD

**Issue by chainray01** [JetBrains/intellij-platform-gradle-plugin#1624]
### What happened?

[gradle-intellij-plugin :] Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'
[gradle-intellij-plugin :runIde] Cannot find prefix in com.dd.plist.NSDictionary@28e961de
[gradle-intellij-plugin :] Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'

### Relevant log output or stack trace

```shell
[gradle-intellij-plugin :] Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'
> Task :initializeIntelliJPlugin SKIPPED
> Task :patchPluginXml UP-TO-DATE

> Task :verifyPluginConfiguration
[gradle-intellij-plugin :verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 173.0 < 203.
- The Java configuration specifies targetCompatibility=11 but since-build='173.0' property requires targetCompatibility=1.8.
See: https://jb.gg/intellij-platform-versions

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :instrumentedJar
> Task :jar
> Task :prepareSandbox

> Task :runIde
[gradle-intellij-plugin :] Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'
[gradle-intellij-plugin :runIde] Cannot find prefix in com.dd.plist.NSDictionary@28e961de
[gradle-intellij-plugin :] Cannot download JetBrains Java Runtime 'jbr_jcef-11_0_9-osx-aarch64-b1145.21'
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2024-05-20 09:59:22,633 [     93]   WARN -        #com.intellij.idea.Main - Unable to load JNA library (OS: Mac OS X 13.6.6) 
java.lang.UnsatisfiedLinkError: /Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna8882808056930175464.tmp: dlopen(/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna8882808056930175464.tmp, 0x0001): tried: '/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna8882808056930175464.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna8882808056930175464.tmp' (no such file), '/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna8882808056930175464.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.intellij.jna.JnaLoader.load(JnaLoader.java:17)
	at com.intellij.idea.StartupUtil.loadSystemLibraries(StartupUtil.java:640)
	at com.intellij.idea.StartupUtil.lambda$prepareApp$4(StartupUtil.java:232)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-05-20 09:59:26,342 [   3802]   WARN - .intellij.util.EnvironmentUtil - can't get shell environment 
java.lang.RuntimeException: command [/bin/zsh, -l, -i, -c, '/Users/ray.chai/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2020.3/5421f64d5537bbe01a4fbb88f2c8f8154c5aa03f/ideaIU-2020.3/bin/printenv.py' '/var/folders/8b/fdv4z7t51jq1bs0y9_r2qtbr0000gn/T/intellij-shell-env.4978163627513106319.tmp']
	exit code:126 text:0 out:env: python: Permission denied
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadOutputAndEnvs(EnvironmentUtil.java:353)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.readShellEnv(EnvironmentUtil.java:254)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.readShellEnv(EnvironmentUtil.java:269)
	at com.intellij.util.EnvironmentUtil.getShellEnv(EnvironmentUtil.java:204)
	at com.intellij.util.EnvironmentUtil.lambda$loadEnvironment$0(EnvironmentUtil.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
2024-05-20 09:59:27,072 [   4532]   WARN -        #com.intellij.idea.Main -  
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1373)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
	at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:823)
	at com.intellij.idea.StartupUtil$1.invokeAndWait(StartupUtil.java:297)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:139)
	at com.intellij.ide.b.b.Q.b(Q.java:206)
	at com.intellij.ide.b.f.Q.a(Q.java:315)
	at com.intellij.ide.b.f.R.c(R.java:181)
	at com.intellij.ide.b.f.R.a(R.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:95)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:302)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:242)
	at com.intellij.ide.plugins.MainRunner.lambda$start$1(MainRunner.java:41)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: JNA library is not available
	at com.intellij.ui.mac.foundation.Foundation.<clinit>(Foundation.java:32)
	at com.intellij.ui.mac.foundation.Foundation$NSAutoreleasePool.<init>(Foundation.java:489)
	at com.intellij.ui.components.MacScrollBarUI.callMac(MacScrollBarUI.java:200)
	at com.intellij.ui.components.MacScrollBarUI$Native.<init>(MacScrollBarUI.java:300)
	at com.intellij.ui.components.MacScrollBarUI$Style$1.<init>(MacScrollBarUI.java:251)
	at com.intellij.ui.components.MacScrollBarUI$Style.<clinit>(MacScrollBarUI.java:251)
	at com.intellij.ui.components.MacScrollBarUI.installUI(MacScrollBarUI.java:103)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:688)
	at java.desktop/javax.swing.JScrollBar.setUI(JScrollBar.java:210)
	at java.desktop/javax.swing.JScrollBar.updateUI(JScrollBar.java:231)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:182)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:702)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(JScrollPane.java:854)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:300)
	at com.intellij.ide.b.b.H.<init>(H.java:811)
	at com.intellij.ide.b.b.A.p(A.java:811)
	at com.intellij.ide.b.b.A.<init>(A.java:322)
	at com.intellij.ide.b.b.G.a(G.java:150)
	at com.intellij.ide.b.b.G.a(G.java:142)
	at com.intellij.ide.b.b.G.<init>(G.java:53)
	at com.intellij.ide.b.b.U.<init>(U.java:251)
	at com.intellij.ide.b.b.x.b(x.java:52)
	at com.intellij.ide.b.b.x.c(x.java:45)
	at com.intellij.ide.b.f.Q.c(Q.java:320)
	at com.intellij.ide.b.b.Q.a(Q.java:212)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :runIde FAILED
> Task :classpathIndexCleanup SKIPPED
9 actionable tasks: 5 executed, 4 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runIde'.
> Build cancelled while executing task ':runIde'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3m 44s
10:02:59: Task execution finished 'runIde'.
```

### Steps to reproduce

buildscript {
    repositories {

    mavenLocal()
    maven { url=uri("https://maven.aliyun.com/repository/public") }
        mavenCentral()
    }

}
plugins {
    id "org.jetbrains.intellij" version "1.17.3"
}

group = 'cn.wuzhizhan.idea.mybatis'
version = '2020.3'

apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', includes: ['*jar'])
    implementation group: 'com.softwareloop', name: 'mybatis-generator-lombok-plugin', version: '1.0'
    implementation group: 'uk.com.robust-it', name: 'cloning', version: '1.9.2'
    testImplementation group: 'junit', name: 'junit', version: '4.12'
}
buildPlugin {
    buildSearchableOptions.enabled = false
}
intellij {
    version.set("2020.3")
    type.set("IU") // Target IDE Platform
    pluginName.set("free-mybatis-plugin")
    plugins=["coverage","DatabaseTools","com.intellij.spring","java"]
    updateSinceUntilBuild=false
}
//patchPluginXml {
//    sinceBuild="2020.3"
//    targetCompatibility(j)
//}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
tasks {
    runIde{
        intellij{
            autoReloadPlugins.set(false)
        }
    }
}

### Gradle IntelliJ Plugin version

1.17.3

### Gradle version

8.7

### Operating System

macOS

**Comment by xunmenglt** [comment]
how to save it
