### ISSUE TITLE
plugin1.17.3 runIde fail:cannot start ide to debug

### ISSUE THREAD

**Issue by chainray01** [JetBrains/intellij-platform-gradle-plugin#1625]
### What happened?

gradle-intellij-plugin :runIde cannot start the ide 

### Relevant log output or stack trace

```shell
15:01:58: Executing task 'runIde'...

> Task :initializeIntelliJPlugin SKIPPED
> Task :patchPluginXml UP-TO-DATE
> Task :verifyPluginConfiguration
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :instrumentedJar UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE

> Task :runIde
[gradle-intellij-plugin :runIde] Cannot find prefix in com.dd.plist.NSDictionary@28e961de
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2024-05-20 15:01:59,041 [     41]   WARN - .intellij.util.EnvironmentUtil - can't get shell environment 
java.lang.RuntimeException: command [/bin/zsh, -l, -i, -c, '/Users/ray.chai/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIU/2020.3/5421f64d5537bbe01a4fbb88f2c8f8154c5aa03f/ideaIU-2020.3/bin/printenv.py' '/var/folders/8b/fdv4z7t51jq1bs0y9_r2qtbr0000gn/T/intellij-shell-env.17682882088342072581.tmp']
	exit code:126 text:0 out:env: python: Permission denied
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.runProcessAndReadOutputAndEnvs(EnvironmentUtil.java:353)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.readShellEnv(EnvironmentUtil.java:254)
	at com.intellij.util.EnvironmentUtil$ShellEnvReader.readShellEnv(EnvironmentUtil.java:269)
	at com.intellij.util.EnvironmentUtil.getShellEnv(EnvironmentUtil.java:204)
	at com.intellij.util.EnvironmentUtil.lambda$loadEnvironment$0(EnvironmentUtil.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2024-05-20 15:01:59,067 [     67]   WARN -        #com.intellij.idea.Main - Unable to load JNA library (OS: Mac OS X 13.6.6) 
java.lang.UnsatisfiedLinkError: /Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna17867639651177174636.tmp: dlopen(/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna17867639651177174636.tmp, 0x0001): tried: '/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna17867639651177174636.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna17867639651177174636.tmp' (no such file), '/Users/ray.chai/IdeaProjects/ideaaction/build/idea-sandbox/system/tmp/jna17867639651177174636.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.intellij.jna.JnaLoader.load(JnaLoader.java:17)
	at com.intellij.idea.StartupUtil.loadSystemLibraries(StartupUtil.java:640)
	at com.intellij.idea.StartupUtil.lambda$prepareApp$4(StartupUtil.java:232)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:187)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
2024-05-20 15:02:01,430 [   2430]   WARN -        #com.intellij.idea.Main -  
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1373)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1348)
	at com.intellij.idea.StartupUtil.runInEdtAndWait(StartupUtil.java:823)
	at com.intellij.idea.StartupUtil$1.invokeAndWait(StartupUtil.java:297)
	at com.intellij.util.ui.EdtInvocationManager.invokeAndWaitIfNeeded(EdtInvocationManager.java:139)
	at com.intellij.ide.b.b.Q.b(Q.java:206)
	at com.intellij.ide.b.f.Q.a(Q.java:315)
	at com.intellij.ide.b.f.R.c(R.java:181)
	at com.intellij.ide.b.f.R.a(R.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.idea.MainImpl.start(MainImpl.java:95)
	at com.intellij.idea.StartupUtil.startApp(StartupUtil.java:302)
	at com.intellij.idea.StartupUtil.prepareApp(StartupUtil.java:242)
	at com.intellij.ide.plugins.MainRunner.lambda$start$1(MainRunner.java:41)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.AssertionError: JNA library is not available
	at com.intellij.ui.mac.foundation.Foundation.<clinit>(Foundation.java:32)
	at com.intellij.ui.mac.foundation.Foundation$NSAutoreleasePool.<init>(Foundation.java:489)
	at com.intellij.ui.components.MacScrollBarUI.callMac(MacScrollBarUI.java:200)
	at com.intellij.ui.components.MacScrollBarUI$Native.<init>(MacScrollBarUI.java:300)
	at com.intellij.ui.components.MacScrollBarUI$Style$1.<init>(MacScrollBarUI.java:251)
	at com.intellij.ui.components.MacScrollBarUI$Style.<clinit>(MacScrollBarUI.java:251)
	at com.intellij.ui.components.MacScrollBarUI.installUI(MacScrollBarUI.java:103)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:688)
	at java.desktop/javax.swing.JScrollBar.setUI(JScrollBar.java:210)
	at java.desktop/javax.swing.JScrollBar.updateUI(JScrollBar.java:231)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:165)
	at java.desktop/javax.swing.JScrollBar.<init>(JScrollBar.java:182)
	at java.desktop/javax.swing.JScrollPane$ScrollBar.<init>(JScrollPane.java:702)
	at java.desktop/javax.swing.JScrollPane.createVerticalScrollBar(JScrollPane.java:854)
	at java.desktop/javax.swing.JScrollPane.<init>(JScrollPane.java:300)
	at com.intellij.ide.b.b.H.<init>(H.java:811)
	at com.intellij.ide.b.b.A.p(A.java:811)
	at com.intellij.ide.b.b.A.<init>(A.java:322)
	at com.intellij.ide.b.b.G.a(G.java:150)
	at com.intellij.ide.b.b.G.a(G.java:142)
	at com.intellij.ide.b.b.G.<init>(G.java:53)
	at com.intellij.ide.b.b.U.<init>(U.java:251)
	at com.intellij.ide.b.b.x.b(x.java:52)
	at com.intellij.ide.b.b.x.c(x.java:45)
	at com.intellij.ide.b.f.Q.c(Q.java:320)
	at com.intellij.ide.b.b.Q.a(Q.java:212)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

> Task :classpathIndexCleanup SKIPPED

BUILD SUCCESSFUL in 12s
9 actionable tasks: 2 executed, 7 up-to-date
15:02:10: Task execution finished 'runIde'.
```

### Steps to reproduce

```
buildscript {
    repositories {
    mavenLocal()
    maven { url=uri("https://maven.aliyun.com/repository/public") }
        mavenCentral()
    }

}
plugins {
    id "org.jetbrains.intellij" version "1.17.3"
}

group = 'cn.wuzhizhan.idea.mybatis'
version = '2020.3'

apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', includes: ['*jar'])
    implementation group: 'com.softwareloop', name: 'mybatis-generator-lombok-plugin', version: '1.0'
    implementation group: 'uk.com.robust-it', name: 'cloning', version: '1.9.2'
    testImplementation group: 'junit', name: 'junit', version: '4.12'
}
buildPlugin {
    buildSearchableOptions.enabled = false
}
intellij {
    version.set("2020.3")
    type.set("IU") // Target IDE Platform
    pluginName.set("free-mybatis-plugin")
    plugins=["coverage","DatabaseTools","com.intellij.spring","java"]
    updateSinceUntilBuild=false
}
patchPluginXml {
    sinceBuild="2020.3"
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
tasks {
    runIde{
        jbrVersion.set("jbr_jcef-11_0_10b1145.115")
    }
}
```

### Gradle IntelliJ Plugin version

1.17.3

### Gradle version

8.7

### Operating System

macOS

**Comment by chainray01** [comment]
https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/5676095/881664e2-392f-4572-b79b-7ada5915ea08

**Comment by hsz** [comment]
Thanks for reporting.
What is the reason for using `2020.3` still as a target platform?

JNA issue happens when you use JBR incompatible with your OS. Assuming, you use macOS with M1 chip, the JBR should be used in ``aarch64` variant.

**Comment by chainray01** [comment]
> Thanks for reporting. What is the reason for using `2020.3` still as a target platform?
> 
> JNA issue happens when you use JBR incompatible with your OS. Assuming, you use macOS with M1 chip, the JBR should be used in `aarch64` variant.

I've checked this m1 mac is used `jbr_jcef-11_0_10-osx-aarch64-b1145.115`. 
<img width="1000" alt="image" src="https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/5676095/9c7b6cd2-0788-47e3-82e8-5fa059cf3690">

i'll  try to upgrade the target platform and  test it again.

**Comment by chainray01** [comment]
> Thanks for reporting. What is the reason for using `2020.3` still as a target platform?
> 
> JNA issue happens when you use JBR incompatible with your OS. Assuming, you use macOS with M1 chip, the JBR should be used in `aarch64` variant.

I've checked this m1 mac is used `jbr_jcef-11_0_10-osx-aarch64-b1145.115`. 
<img width="1000" alt="image" src="https://github.com/JetBrains/intellij-platform-gradle-plugin/assets/5676095/9c7b6cd2-0788-47e3-82e8-5fa059cf3690">

i'll  try to upgrade the target platform and  test it again.

**Comment by chainray01** [comment]
@hsz I've upgrade target platform to 2024.1, It's works :).

**Comment by hsz** [comment]
Thank you for the confirmation!
