### ISSUE TITLE
bug in prepareKotlinBuildScriptModel

### ISSUE THREAD

**Issue by nikomp** [JetBrains/intellij-platform-gradle-plugin#1626]
### What happened?

I am developing a plugin for Android 2023.3.1 (Build #AI-233.14808.21). When creating a new IDE Plugin in Intellij Idea, I get an error

[gradle-intellij-plugin :] Error when resolving dependency: DefaultExternalModuleDependency{group='com.jetbrains.intellij.idea', name='ideaIC', version='233.14808.21', configuration='default'}
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration5'

Android Studio  2023.3.1
Intellij Idea 2023.3.5

### Relevant log output or stack trace

```shell
> Task :prepareKotlinBuildScriptModel UP-TO-DATE
[gradle-intellij-plugin :] Error when resolving dependency: DefaultExternalModuleDependency{group='com.jetbrains.intellij.idea', name='ideaIC', version='233.14808.21', configuration='default'}
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration5'.
	at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailure(ResolveExceptionContextualizer.java:81)
	at org.gradle.api.internal.artifacts.ResolveExceptionContextualizer.mapFailures(ResolveExceptionContextualizer.java:60)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:2310)
	at org.gradle.api.internal.artifacts.configurations.ResolutionHost.rethrowFailure(ResolutionHost.java:30)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.maybeThrowResolutionFailures(ResolutionBackedFileCollection.java:84)
	at org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection.visitContents(ResolutionBackedFileCollection.java:74)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:359)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:557)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:123)
	at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getFiles(Unknown Source)
	at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromMultipleRepositories(DependenciesDownloader.kt:73)
	at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromRepository(DependenciesDownloader.kt:36)
	at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromRepository$default(DependenciesDownloader.kt:31)
	at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveRemote(IdeaDependencyManager.kt:343)
	at org.jetbrains.intellij.IntelliJPlugin$prepareIdeaDependencyProvider$1.call(IntelliJPlugin.kt:286)
	at ...
```

### Steps to reproduce

I have updated intellij Idea and am trying to create a new IDE Plugin

### Gradle IntelliJ Plugin version

1.16.1

### Gradle version

gradle-wrapper

### Operating System

None

**Comment by hsz** [comment]
Hey, Nikolay!

In the first place, please upgrade the Gradle IntelliJ Plugin to the latest version available: `1.17.3` or `2.0.0-beta3`.

After upgrading, please try again and if the issue persists, provide your Gradle build file for the further investigation.
