### ISSUE TITLE
2.0 - Junit4 test framework has an implicit dependency on idea-rt

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/intellij-platform-gradle-plugin#1632]
### What happened?

The test framework `CodeInsightTestFixtureImpl` still has a hard dependency on `idea-java-rt` module causing the usages of the the test frameworks outside of IntelliJ IDEA platform to fail

Offending code is still in `master` through the use of the deprecated class

https://github.com/JetBrains/intellij-community/blob/2a1fae66a2ce042315ac04c153d816333db3c4bd/platform/testFramework/src/com/intellij/testFramework/fixtures/impl/CodeInsightTestFixtureImpl.java#L127

I am not expecting a fix for this in this plugin, but maybe IDE platform team can fix the dependency for future versions?

### Relevant log output or stack trace

```shell
java.lang.NoClassDefFoundError: com/intellij/rt/execution/junit/FileComparisonFailure
	at com.intellij.testFramework.fixtures.impl.IdeaTestFixtureFactoryImpl.createCodeInsightFixture(IdeaTestFixtureFactoryImpl.java:80)
	at PHPFixtureTestCase$fixtureRule$1.before(PHPFixtureTestCase.kt:29)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.ClassNotFoundException: com.intellij.rt.execution.junit.FileComparisonFailure
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:224)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 40 more
```

### Steps to reproduce

Use the following settings

```
    intellijPlatform {
        phpstorm(project.providers.gradleProperty("buildPlatformVersion"))
        bundledPlugins("com.jetbrains.php")

        testFramework(TestFrameworkType.Platform.JUnit4)
    }
```

unit test:
```
            val testFixture = IdeaTestFixtureFactory.getFixtureFactory()
                    .createLightFixtureBuilder(LightProjectDescriptor(), testName.methodName).fixture
            fixture = IdeaTestFixtureFactory.getFixtureFactory()
                    .createCodeInsightFixture(testFixture, LightTempDirTestFixtureImpl(true))
            fixture.setUp()
```

### Gradle IntelliJ Plugin version

2.0.0-beta3

### Gradle version

8.7

### Operating System

None

**Comment by YannCebron** [comment]
Thanks for submitting this issue, following up with IJ Platform team on it.

**Comment by YannCebron** [comment]
https://youtrack.jetbrains.com/issue/IJPL-156277/Remove-the-FIleComparisonFailure-and-FileComparisonData-classes-and-their-support
