### ISSUE TITLE
Add support for mute switch for plugin verifier

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/intellij-platform-gradle-plugin#1646]
### Describe the need of your request

The latest release of the plugin verifier (https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/1.367) added a `-mute` switch.

Can this be exposed as a `ListProperty<String>` on the verifier block?

### Proposed solution

Add new provider on the verifier config

**Comment by YannCebron** [comment]
There's already https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#verifyPlugin-freeArgs which should work. I don't think it makes sense to expose this via dedicated property, given the total number of affected plugins.

**Comment by vsaar** [comment]
I tried to mute some errors with `freeArgs`, since my plugin has the `intellij` identifier in its name and title:
```
    verifyPlugin {
        ides {
            recommended()
        }
        freeArgs = listOf("-mute TemplateWordInPluginId,TemplateWordInPluginName")
    }
```

However, this results in the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException: IDE must reside in a directory: <path-to-plugin>/build/distributions/plugin-1.11.0.zip
 	at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:103)
 	at com.jetbrains.pluginverifier.tasks.checkPlugin.DefaultIdeDescriptorParser.parseIdeDescriptors(CheckPluginParamsBuilder.kt:126)
 	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:41)
 	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:27)
 	at com.jetbrains.pluginverifier.PluginVerifierMain$main$3$1.invoke(PluginVerifierMain.kt:130)
 	at com.jetbrains.pluginverifier.PluginVerifierMain$main$3$1.invoke(PluginVerifierMain.kt:123)
 	at com.jetbrains.pluginverifier.tasks.profiling.PluginVerificationProfilingsKt.measurePluginVerification(PluginVerificationProfilings.kt:11)
 	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:123)
```

The command line that is generated looks okay to me, so maybe it's an issue with the plugin verifier itself.

**Comment by abrooksv** [comment]
@vsaar you need to split the list

```
        freeArgs = listOf(
            "-mute",
            "TemplateWordInPluginId"
        )
```

**Comment by vsaar** [comment]
@abrooksv, thanks, that worked. Though it's not very intuitive.

**Comment by YannCebron** [comment]
Documented https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-faq.html#how-to-mute-specific-problems-in-verifyplugin

**Comment by Macariel** [comment]
I just want to comment that the problem of not splitting up the single arguments leading to the error `IDE must reside in directory`  has led me on the wildest goose chase. 
This is probably a case of a problem not being caught at the right place and in combination with the inability to debug Gradle (in Intellij) and some outdated documentation (even though the plugin was just released), see [downloadDirectory](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginVerification-downloadDirectory), which doesn't exist, leads to a very frustrating experience.

**Comment by abrooksv** [comment]
@Macariel You can usually debug gradle (as far as gradle is debuggable...) by enabling Gradle script debugging

<img width="846" alt="Screenshot 2024-08-02 at 8 22 45 AM" src="https://github.com/user-attachments/assets/bcb2b97b-c51d-42bb-84fc-c994c5a808b4">
