### ISSUE TITLE
Illegal char <:> at index 5: https://issuetracker.google.com/issues/new?component

### ISSUE THREAD

**Issue by MaxMichel2** [JetBrains/intellij-platform-gradle-plugin#1683]
### What happened?

After a successful sync, trying to run the `runIde`, the task fails with the issue in the title (detailed logs below)

### Relevant log output or stack trace

```shell
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://issuetracker.google.com/issues/new?component	
at org.jetbrains.intellij.Utils.resolveIdeHomeVariable(utils.kt:107)	
at org.jetbrains.intellij.propertyProviders.LaunchSystemArgumentProvider.getCurrentLaunchProperties(LaunchSystemArgumentProvider.kt:27)	
at org.jetbrains.intellij.propertyProviders.LaunchSystemArgumentProvider.asArguments(LaunchSystemArgumentProvider.kt:30)	
at org.jetbrains.intellij.propertyProviders.LaunchSystemArgumentProvider.asArguments(LaunchSystemArgumentProvider.kt:14)	
...
at org.jetbrains.intellij.tasks.RunIdeBase.exec(RunIdeBase.kt:199)
```

### Steps to reproduce

Add a `runIde` block with a specified `ideDir` similarly to the following:

```
runIde {
    ideDir.set(file(properties("androidStudioRunPath").get()))
}
```

Note that `androidStudioRunPath` is defined as: `C:/Users/<user>/AppData/Local/Programs/Android Studio`

Also add `platformPlugins = android`

### Gradle IntelliJ Plugin version

1.17.4

### Gradle version

8.6

### Operating System

Windows

**Comment by MaxMichel2** [comment]
This issue may relate in some way to #1398

**Comment by hsz** [comment]
Please see #1585
