### ISSUE TITLE
collectBundledPluginsJars returning a relative path outside the platform root

### ISSUE THREAD

**Issue by brian-mcnamara** [JetBrains/intellij-platform-gradle-plugin#1692]
### What happened?

When I try to sync the plugin in IJ, I'm getting and error. Upon digging into the issue `collectBundledPluginsJars` is returning a single entry `lib/marketplace-zip-signer-cli.jar` 

### Relevant log output or stack trace

```shell
Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
	at org.jetbrains.intellij.platform.gradle.providers.ModuleDescriptorsValueSource.obtain(ModuleDescriptorsValueSource.kt:50)
	at org.jetbrains.intellij.platform.gradle.providers.ModuleDescriptorsValueSource.obtain(ModuleDescriptorsValueSource.kt:25)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtain(DefaultValueSourceProviderFactory.java:301)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:256)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:80)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.createPlatformDependency(IntelliJPlatformDependenciesHelper.kt:731)
	at org.jetbrains.intellij.platform.gradle.extensions.IntelliJPlatformDependenciesHelper.access$createPlatformDependency(IntelliJPlatformDependenciesHelper.kt:58)
```

### Steps to reproduce

It looks to be that I have that file under my root project under lib/marketplace-zip-signer-cli.jar, so for some reason, the collectBundledPluginsJars method is including files under my project (no idea how it gets there.)

### Gradle IntelliJ Plugin version

2.0.0-beta8

### Gradle version

8.5

### Operating System

macOS

**Comment by hsz** [comment]
Thank you, Brian!
Fixed with https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/1e0f20fe8b250c1cf9a3f1dbf6ef9b8a0e7ed3bf
