### ISSUE TITLE
ProductReleasesValueSource.FilterParameters.sinceBuild is marked optional, when its required

### ISSUE THREAD

**Issue by brian-mcnamara** [JetBrains/intellij-platform-gradle-plugin#1700]
### What happened?

I'm using ProductReleasesValueSource to fetch the latest EAP version, and ran into an exception because on line 147 its expected the input is provided. 

That said, it would be nice if this could be refactored in such a way that given the channel and type, we could find the latest version and sinceBuild could be optional in that case

### Relevant log output or stack trace

```shell
org.gradle.api.internal.provider.MissingValueException: Cannot query the value of this provider because it has no value available.
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateOwnPresentValue(AbstractMinimalProvider.java:82)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:100)
	at org.jetbrains.intellij.platform.gradle.providers.ProductReleasesValueSource.obtain(ProductReleasesValueSource.kt:147)
	at org.jetbrains.intellij.platform.gradle.providers.ProductReleasesValueSource.obtain(ProductReleasesValueSource.kt:39)
	at org.gradle.internal.Try.ofFailable(Try.java:41)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$LazilyObtainedValue.obtain(DefaultValueSourceProviderFactory.java:301)
	at org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$ValueSourceProvider.calculateOwnValue(DefaultValueSourceProviderFactory.java:256)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:82)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.BiProvider.calculateOwnValue(BiProvider.java:68)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:115)
	at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:100)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:334)
	at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:329)
	at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource$Element.realize(AbstractIterationOrderRetainingElementSource.java:346)
	at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource.realizePending(AbstractIterationOrderRetainingElementSource.java:143)
	at org.gradle.api.internal.DefaultDomainObjectCollection.addEagerAction(DefaultDomainObjectCollection.java:224)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:142)
	at org.gradle.api.internal.CompositeDomainObjectSet.addCollection(CompositeDomainObjectSet.java:114)
	at org.gradle.api.internal.CompositeDomainObjectSet.create(CompositeDomainObjectSet.java:58)
	at org.gradle.api.internal.collections.DefaultDomainObjectCollectionFactory.newDomainObjectSet(DefaultDomainObjectCollectionFactory.java:112)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.initAllDependencies(DefaultConfiguration.java:950)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getAllDependencies(DefaultConfiguration.java:936)
	at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getAllDependencies(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.initAllDependencies(DefaultConfiguration.java:952)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getAllDependencies(DefaultConfiguration.java:936)
	at org.gradle.api.internal.artifacts.configurations.DefaultUnlockedConfiguration_Decorated.getAllDependencies(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies.getDependencies(DefaultConfiguration.java:2056)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationResolvableDependencies_Decorated.getDependencies(Unknown Source)
	at org.jetbrains.intellij.platform.gradle.plugins.project.IntelliJPlatformBasePlugin$apply$3$intellijPlatformConfiguration$1$2.execute(IntelliJPlatformBasePlugin.kt:136)
	at org.jetbrains.intellij.platform.gradle.plugins.project.IntelliJPlatformBasePlugin$apply$3$intellijPlatformConfiguration$1$2.execute(IntelliJPlatformBasePlugin.kt:135)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:99)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:87)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:268)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:170)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:381)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:272)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:148)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
```

### Steps to reproduce

```
    fun getEapVersion(project: Project) =
        project.providers.of(ProductReleasesValueSource::class.java) {
            parameters.jetbrainsIdesUrl.set(Constants.Locations.PRODUCTS_RELEASES_JETBRAINS_IDES)
            parameters.channels.set(listOf(ProductRelease.Channel.EAP))
            parameters.types.set(listOf(IntelliJPlatformType.IntellijIdeaCommunity))
        }.map { versions -> versions.map { Version.parse(it) }.maxOf { it } }.map { with (it) {"$major.$minor.$patch"} }
```

### Gradle IntelliJ Plugin version

2.0.0-beta9

### Gradle version

8.5

### Operating System

macOS

**Comment by brian-mcnamara** [comment]
It also seems `.map { it.maxBy { release -> release.version } }` is not returning the right entry. Currently, its returning `242.19890.14` when `242.20224.38` is the latest

**Comment by brian-mcnamara** [comment]
Just a thought, but could we have another value source that provides the sequence and allows implementors to filter themselves?

**Comment by hsz** [comment]
Thanks for reporting, Brian!

The issue you mention in the first post is already fixed with: https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/1a8ba095762d71eae4a8e25f8b8ed213aa2a71d3

It is also possible to specify a custom URL for the JetBrains IDEs and Android Studio release listing: https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1686#issuecomment-2221297523

```
org.jetbrains.intellij.platform.productsReleasesAndroidStudioUrl=https://jb.gg/android-studio-releases-list.xml
org.jetbrains.intellij.platform.productsReleasesJetBrainsIdesUrl=https://www.jetbrains.com/updates/updates.xml
```

If you want to use a custom value source, I think it'd be easier for both of us to go with `ides(List<String>)`. You need to pass there a list of notations in `TYPE-VERSION` format:

```kotlin
intellijPlatform {
  verifyPlugin {
    ides {
      ides(notations: List<String>)
    }
  }
}
```

As for the `maxBy` issue — nice catch! Fixed with: https://github.com/JetBrains/intellij-platform-gradle-plugin/commit/da8ffb7470de975bd83707a2588345e3166fe417

**Comment by brian-mcnamara** [comment]
Thanks @hsz !

Regarding the custom url, unfortunately I need to add credentials to the request, so Ill poke around with this
