### ISSUE TITLE
v2: No IDE resolved for verification with the IntelliJ Plugin Verifier

### ISSUE THREAD

**Issue by WarningImHack3r** [JetBrains/intellij-platform-gradle-plugin#1717]
### What happened?

When running the plugin verifier task, I get the same error for both of my plugins:
```
* What went wrong:
Execution failed for task ':verifyPlugin'.
> No IDE resolved for verification with the IntelliJ Plugin Verifier.
  Please ensure the `intellijPlatform.pluginVerification.ides` extension block is configured along with the `defaultRepositories()` (or at least `localPlatformArtifacts()`) entry in the repositories section.
  See: https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginVerification-ides
```

[I migrated](https://github.com/WarningImHack3r/npm-update-dependencies/pull/116) using the default [template 2.0.0 changes](https://github.com/JetBrains/intellij-platform-plugin-template/pull/458/files)

### Relevant log output or stack trace

```shell
See GH Action

I also have this exception in :buildSearchableOptions:
2024-07-31 23:17:46,214 [    727]   WARN - o.j.n.NativeTrustedRootsInternalUtils - Unable to get custom trusted certificates list from the operating system: java.security.cert.CertificateParsingException: Empty issuer DN not allowed in X509Certificates
java.lang.RuntimeException: java.security.cert.CertificateParsingException: Empty issuer DN not allowed in X509Certificates
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.getX509Certificate(SecurityFrameworkUtil.java:92)
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.isTrustedRoot(SecurityFrameworkUtil.java:113)
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.lambda$getTrustedRoots$0(SecurityFrameworkUtil.java:31)
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.SecTrustSettingsCopyCertificates(SecurityFrameworkUtil.java:72)
	at org.jetbrains.nativecerts.mac.SecurityFrameworkUtil.getTrustedRoots(SecurityFrameworkUtil.java:31)
	at org.jetbrains.nativecerts.NativeTrustedCertificates.getCustomOsSpecificTrustedCertificates(NativeTrustedCertificates.java:34)
	at com.intellij.util.net.ssl.OsCertificatesServiceImpl.getCustomOsSpecificTrustedCertificates(OsCertificatesServiceImpl.java:14)
	at com.intellij.util.net.ssl.ConfirmingTrustManager.getOperatingSystemTrustManager(ConfirmingTrustManager.java:96)
	at com.intellij.util.net.ssl.ConfirmingTrustManager.getSystemTrustManagers(ConfirmingTrustManager.java:61)
	at com.intellij.util.net.ssl.ConfirmingTrustManager.createForStorage(ConfirmingTrustManager.java:54)
	at com.intellij.util.net.ssl.CertificateManager$trustManager$2.invoke(CertificateManager.kt:63)
	at com.intellij.util.net.ssl.CertificateManager$trustManager$2.invoke(CertificateManager.kt:62)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.util.net.ssl.CertificateManager.getTrustManager(CertificateManager.kt:62)
	at com.intellij.util.net.ssl.CertificateManager.calcSslContext(CertificateManager.kt:284)
	at com.intellij.util.net.ssl.CertificateManager.access$calcSslContext(CertificateManager.kt:58)
	at com.intellij.util.net.ssl.CertificateManager$sslContext$2.invoke(CertificateManager.kt:82)
	at com.intellij.util.net.ssl.CertificateManager$sslContext$2.invoke(CertificateManager.kt:82)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.util.net.ssl.CertificateManager.getSslContext(CertificateManager.kt:82)
	at com.intellij.util.net.ssl.CertificateManager$1.invokeSuspend(CertificateManager.kt:91)
```

### Steps to reproduce

1) Have a plugin using the template 1.14.2
2) Perform the upgrade to 2.0.0
3) Run the plugin verifier task locally or on CI

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.9

### Operating System

macOS

### Link to build, i.e. failing GitHub Action job

https://github.com/WarningImHack3r/npm-update-dependencies/actions/runs/10180397458/job/28158305904?pr=116

**Comment by hsz** [comment]
Gradle doesn't like the empty value passed to `untilBuild`.
For now, in your Gradle build script, use `untilBuild = provider { null }` if you want to unset that constraint.

**Comment by WarningImHack3r** [comment]
> in your Gradle build script, use `untilBuild = provider { null }`

I instead added that as a fallback:
```kotlin
ideaVersion {
    sinceBuild = providers.gradleProperty("pluginSinceBuild")
    untilBuild = providers.gradleProperty("pluginUntilBuild").map { it.ifBlank { null } }
}
```
And it works like a charm!

About the X509 issue I mentioned in the stack trace above: I still have it, should I open another issue?

**Comment by hsz** [comment]
Thank you for the confirmation. I have pushed the same `it.ifBlank { null }` fix to the repository.

As for the X509 exception, it happens on the IDE side and also depends on the IntelliJ Platform you use for development.
The `buildSearchableOptions` task runs IDE in headless mode for building extra metadata about searchable items present in your plugin. If the same issue happens with newer IDEs, it'd be worth reporting to youtrack.jetbrains.com (IDEA project).

**Comment by WarningImHack3r** [comment]
@hsz I now get this error with 2024.2, it doesn't prevent it from still working though
![CleanShot 2024-08-09 at 18 24 52@2x](https://github.com/user-attachments/assets/e2314eaf-fc20-4b49-a850-d82008d6d95e)

**Comment by hsz** [comment]
Can you remove your `.map {}` and check if everything works as expected?

**Comment by WarningImHack3r** [comment]
> Can you remove your `.map {}` and check if everything works as expected?

![CleanShot 2024-08-09 at 18 39 27@2x](https://github.com/user-attachments/assets/a86cf985-0885-41df-b3a0-8744a9580265)

Does not, already tried (using the very latest versions of everything)

**Comment by WarningImHack3r** [comment]
Update for whoever has the same problem:
```kotlin
untilBuild = providers.gradleProperty("pluginUntilBuild").takeIf {
    !it.orNull.isNullOrBlank()
} ?: provider { null }
```
is both accepted by the IDE and working as expected with the Plugin Verifier.
