### ISSUE TITLE
verifyPlugin fails against ideaIC-242.20224.159-win

### ISSUE THREAD

**Issue by jhonnen** [JetBrains/intellij-platform-gradle-plugin#1719]
### What happened?

I'm running `verifyPlugin` with the following config:

* `intellijPlatform.pluginVerification.ides.recommended()`
* `untilBuild = "300.*"`

And it fails due to a missing plugin in `ideaIC-242.20224.159-win`. Not sure if that's actually a bug in this Gradle plugin or in the verifier or in this specific build itself.

### Relevant log output or stack trace

```shell
> Task :<project>:verifyPlugin
Exception in thread "main" java.lang.IllegalArgumentException: Plugin file D:\dev\.home\.gradle\caches\8.9\transforms\6ec5f904de32e0588aa82d88a623c817\transformed\ideaIC-242.20224.159-win\plugins\emojipicker\lib\emojipicker.jar does not exist
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.getPluginCreatorWithResult(IdePluginManager.kt:374)
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.createBundledPlugin(IdePluginManager.kt:351)
	at com.jetbrains.plugin.structure.intellij.plugin.IdePluginManager.createBundledPlugin$default(IdePluginManager.kt:349)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager.createPlugin(ProductInfoBasedIdeManager.kt:136)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager.access$createPlugin(ProductInfoBasedIdeManager.kt:41)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager$readPlugins$pluginFactory$1.invoke(ProductInfoBasedIdeManager.kt:77)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager$readPlugins$pluginFactory$1.invoke(ProductInfoBasedIdeManager.kt:41)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManagerKt$sam$com_jetbrains_plugin_structure_ide_layout_LayoutComponentLoader$0.load(ProductInfoBasedIdeManager.kt)
	at com.jetbrains.plugin.structure.ide.layout.PluginFactory.read(PluginFactory.kt:23)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager.readPlugins(ProductInfoBasedIdeManager.kt:86)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager.createIde(ProductInfoBasedIdeManager.kt:63)
	at com.jetbrains.plugin.structure.ide.ProductInfoBasedIdeManager.createIde(ProductInfoBasedIdeManager.kt:52)
	at com.jetbrains.plugin.structure.ide.DispatchingIdeManager.createIde(DispatchingIdeManager.kt:19)
	at com.jetbrains.plugin.structure.ide.DispatchingIdeManager.createIde(DispatchingIdeManager.kt:11)
	at com.jetbrains.pluginverifier.ide.IdeDescriptor$Companion.create(IdeDescriptor.kt:60)
	at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:114)
	at com.jetbrains.pluginverifier.options.OptionsParser.createIdeDescriptor(OptionsParser.kt:105)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.DefaultIdeDescriptorParser.parseIdeDescriptors(CheckPluginParamsBuilder.kt:126)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:41)
	at com.jetbrains.pluginverifier.tasks.checkPlugin.CheckPluginParamsBuilder.build(CheckPluginParamsBuilder.kt:27)
	at com.jetbrains.pluginverifier.PluginVerifierMain$main$3$1.invoke(PluginVerifierMain.kt:130)
	at com.jetbrains.pluginverifier.PluginVerifierMain$main$3$1.invoke(PluginVerifierMain.kt:123)
	at com.jetbrains.pluginverifier.tasks.profiling.PluginVerificationProfilingsKt.measurePluginVerification(PluginVerificationProfilings.kt:11)
	at com.jetbrains.pluginverifier.PluginVerifierMain.main(PluginVerifierMain.kt:123)
```

### Steps to reproduce

see above

### Gradle IntelliJ Plugin version

2.0.0

### Gradle version

8.9

### Operating System

Windows

**Comment by YannCebron** [comment]
Please watch https://youtrack.jetbrains.com/issue/MP-6708

**Comment by YannCebron** [comment]
Also, do not use made-up build number like `untilBuild = "300.*"`, see https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity

**Comment by jhonnen** [comment]
> Also, do not use made-up build number like `untilBuild = "300.*"`, see https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#build-number-validity

Thanks for the hint! I explicitly don't want to restrict the untilBuild for this internally used plugin. But the following also works for me:

    intellijPlatform {
        pluginConfiguration.ideaVersion {
            untilBuild.unset() // declare compatibility with all future builds
        }
        pluginVerification.ides.select { 
            untilBuild = "*"
        }
    }

**Comment by YannCebron** [comment]
@jhonnen please see https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-extension.html#intellijPlatform-pluginConfiguration-ideaVersion-untilBuild on how to set "unlimited until-build"
