### ISSUE TITLE
SLF4J providers clashing

### ISSUE THREAD

**Issue by sebastiangolec** [JetBrains/intellij-platform-gradle-plugin#1740]
### What happened?

IntelliJ Platform Gradle Plugin 2.0 adds SLF4J provider that is clashing with Spring Dependencies.

**Logs:**
``` Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
SLF4J: Class path contains multiple SLF4J providers.
SLF4J: Found provider [org.slf4j.jul.JULServiceProvider@15b3e5b]
SLF4J: Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@61ca2dfa]
SLF4J: See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual provider is of type [org.slf4j.jul.JULServiceProvider@15b3e5b]
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.jul.JDK14LoggerFactory loaded from file:/Users/sebastiangolec/.gradle/caches/8.9/transforms/c05e03cd01f6cc27cf1e6f1ef580caa0/transformed/ideaIU-2024.2.0.1/lib/util-8.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.jul.JDK14LoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:592)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:511)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:401)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:128)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:238)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:220)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$starting$0(SpringApplicationRunListeners.java:54)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at io.github.sebastiangolec.stalmixpipes.Main.main(Main.java:10)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 2 more
Process finished with exit code 0
```

**build.gradle.kts file:**
```
plugins {
    java
    id("org.jetbrains.intellij.platform") version "2.0.1"
    id("org.springframework.boot") version "3.3.2"
    id("io.spring.dependency-management") version "1.1.6"
}

group = "io.github.sebastiangolec"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()

    }
}

dependencies {
    intellijPlatform {
        intellijIdeaUltimate("2024.2")
        instrumentationTools()
        pluginVerifier()
        zipSigner()
    }

    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("com.h2database:h2") // only for development
    implementation("org.liquibase:liquibase-core")
    compileOnly("org.springframework.boot:spring-boot-devtools") // only for development
//    runtimeOnly("org.postgresql:postgresql")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.withType<Test> {
    useJUnitPlatform()
    val javaToolchains = project.extensions.getByType<JavaToolchainService>()
    javaLauncher.set(javaToolchains.launcherFor {
        languageVersion.set(JavaLanguageVersion.of(21))
    })
}
```

### Steps to reproduce

Run project with Gradle plugin and Spring Boot Starter Web dependency

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.9

### Operating System

macOS

**Comment by AlexanderBartash** [comment]
You should exclude all logging frameworks from all dependencies in your plugin, because the IDE provides them already https://blog.jetbrains.com/platform/2022/02/removing-log4j-from-the-intellij-platform/ if you include e.g. slf4j in your plugin it may break logging from other libs.
