### ISSUE TITLE
Download intellij platform sources does nothing

### ISSUE THREAD

**Issue by jonathanlermitage** [JetBrains/intellij-platform-gradle-plugin#1750]
### What happened?

I opened the `com.intellij.openapi.application.ModalityState` class, and I asked to download intellij platform sources in order to see the `ModalityState.java` sources. I see progress bar saying it's downloading sources, then nothing happen. I still see the "Download intellij platform sources" button, and I don't see the `ModalityState.java` sources.  

Please see uploaded logs and video: Upload id: 2024_08_27_jBSbyVSkvqo9xAgEWYB6Cr (files: 2024-08-27 13-36-35.mkv and 2 more)

### Steps to reproduce

try to open ModalityState and download sources

### Gradle IntelliJ Plugin version

2.0.1

### Gradle version

8.10

### Operating System

Windows

**Comment by hsz** [comment]
Thanks for reporting.

Which IntelliJ Platform do you target?
What happens if you manually trigger the Gradle project refresh after downloading sources?

**Comment by jonathanlermitage** [comment]
I'm targeting IC 2024.2.1.  
I can see sources if I trigger the Gradle project refresh after downloading sources. I have to do this in all my projects.

**Comment by hsz** [comment]
Thanks for confirming. This is a problem that should be somehow addressed within the DevKit plugin inside the IntelliJ IDEA.

Related issue: https://youtrack.jetbrains.com/issue/IJPL-158473/Support-more-cases-of-attaching-IntelliJ-Platform-sources-by-DevKit-plugin

**Comment by PHPirates** [comment]
For me, an extra Gradle sync does not work on Linux (it works fine on Windows), but the following process seems to do it:

* Click 'Download sources' after opening a class file
* Sync Gradle project
* Invalidate caches & restart
* Sync Gradle project (twice?)
* Open class file and select 'Download sources' again
* Now I can click 'open source file'

**Comment by tamj0rd2** [comment]
> Which IntelliJ Platform do you target?
What happens if you manually trigger the Gradle project refresh after downloading sources?

I'm targeting IU 2024.3.3. Triggering the gradle project refresh after downloading the sources doesn't do anything for me. [These steps](https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1750#issuecomment-2589185045) also didn't work

**Comment by chylex** [comment]
Targeting IC 2024.3 in a fork of IdeaVim, it doesn't work for me even if I manually find the sources jar...

I don't know if it's caused by the awful decision to make IntelliJ no longer download sources by default, or some bug in the gradle plugin, but the fact I can't even tell between the two is unbelievably frustrating. I already have "Download sources" enabled in the "Advanced Settings", because wanting a functioning IDE is an "advanced" feature apparently. It doesn't even work.

2+ years ago this basic plugin development feature worked fine, at least when targeting IC. Now it's constantly broken.

**Comment by lynnfield** [comment]
I had a similar issue: sometimes the sources had downloaded, but nothing happened, and sometimes they failed to download.
In my case, the problem was that I created my plugin as a module, so my `settings.gradle.kts` is not the same as in the IDEA plugin template.
What helped me is explicitly adding [releases repo](https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html#gradle-example-for-an-individual-module-from-the-intellij-platform) to `settings.gradle.kts`

```kotlin
dependencyResolutionManagement {
    repositories {
        // ... other repos ....
        maven("https://www.jetbrains.com/intellij-repository/releases") // <- this helped
    }
}
```

**Comment by hsz** [comment]
This should now be resolved.

Resolving IntelliJ Platform sources works correctly with the latest releases of the Plugin DevKit plugin, which is where the "Download IntelliJ Platform sources" / attach behavior lives (IJPL-158473).

On the Gradle side, the recent [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template) and projects generated with the New Project Wizard preconfigure all required repositories in `settings.gradle.kts`, so they are available to every module and the `-sources.jar` artifacts can be found and attached correctly.

If you start from an up-to-date template/Wizard project and use a current DevKit build, the sources should resolve and open without the manual re-sync workarounds mentioned earlier in this thread. Please give it a try and let us know if you still run into it on the latest versions.

**Comment by chylex** [comment]
Is it supposed to work with Plugin DevKit 262.10315.69 and platform plugin 2.18.1, or in a future version?

My experience working on plugins in the last 2 days, after a long break, has been that I see decompiled sources every time IntelliJ version changes, every time I add a `bundledModule` dependency, sometimes multiple times in a row if the classes are in different jars, and I only finally see sources after some combination of clicking "Download IntelliJ Platform Sources" in the editor notification and "Download Sources" in the Gradle tool window multiple times, and closing and reopening the class file in the editor. It's really, really frustrating.

**Comment by hsz** [comment]
@chylex that's unexpected. Can you please provide more details on that, like a repro project/exact steps? I'll take care of it ASAP.

**Comment by chylex** [comment]
Tried a few things on https://github.com/chylex/IntelliJ-Keyboard-Master, first I changed IJ version to 2025.1 and back, showing that sources are never attached after changing IJ version, and clicking the download button randomly chooses whether to open the sources in the same or separate tab:

https://github.com/user-attachments/assets/412e9704-529e-4f23-9c3d-3769cad8e1e0

Then I added a bundled module and opened a class, showing again that sources are not attached by default anytime a new jar is added to the project. This time, attaching sources went pretty quickly and smoothly at least:

https://github.com/user-attachments/assets/f8c9497d-9c83-4391-9b09-8a85884e27d5

I think the issue with having to click "Download IntelliJ Platform Sources" multiple times was more just a UI problem, maybe the source download was large and IDEA was still doing something in the background, and simply waiting longer would have worked. I noticed this exception/warning from Plugin DevKit at a time when IDEA froze while attaching sources earlier:

```stacktrace
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:378)
	at com.intellij.util.SlowOperations.logError(SlowOperations.java:180)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:128)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecordsImpl.update(FSRecordsImpl.java:790)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findChildInfo(PersistentFSImpl.java:854)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findInPersistence(VirtualDirectoryImpl.java:250)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChildImpl(VirtualDirectoryImpl.java:221)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:132)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:516)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil$1.childOf(VfsImplUtil.java:75)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil$1.childOf(VfsImplUtil.java:63)
	at com.intellij.openapi.vfs.newvfs.FileNavigator.followPath(FileNavigator.java:138)
	at com.intellij.openapi.vfs.newvfs.FileNavigator.lambda$navigate$0(FileNavigator.java:115)
	at com.intellij.openapi.vfs.newvfs.FileNavigator.retryUpToN(FileNavigator.java:172)
	at com.intellij.openapi.vfs.newvfs.FileNavigator.navigate(FileNavigator.java:114)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:78)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:99)
	at com.intellij.openapi.vfs.LocalFileSystem.refreshAndFindFileByNioFile(LocalFileSystem.java:69)
	at com.intellij.jarFinder.InternetAttachSourceProvider.attachSourceJar(InternetAttachSourceProvider.java:297)
	at org.jetbrains.idea.devkit.gradle.IntelliJPlatformAttachSourcesProvider.attachSources$lambda$1(IntelliJPlatformAttachSourcesProvider.kt:310)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:246)
	...
```

However, the main problem is that sources are not being attached by default, so updating IDEA versions for 4 plugins, adding several module and plugin references, and switching between branches targeting different versions, meant that I saw the decompiled sources screen like 20+ times.

**Comment by hsz** [comment]
Thanks for the great follow-up, @chylex!
So, source downloading works, but the UX is a problem here, I agree.

When calling the "Download IntelliJ Platform Sources" action, the Plugin DevKit triggers a temporary Gradle task to resolve sources. And yes, it may take time to get them (~150MB), associate with your IntelliJ Platform dependency, and then _Analyze__ before you see the IDE swapping from the compiled class to an actual source file.

It works like that because we do not publish `-sources.jar` for installers, nor for IDEs different than IC/IU.
All the sources are published to
- https://www.jetbrains.com/intellij-repository/releases
- https://www.jetbrains.com/intellij-repository/snapshots

<img width="1390" height="498" alt="Image" src="https://github.com/user-attachments/assets/be322df6-dec0-417a-b172-1eb281d30203" />

But those are associated with `com.jetbrains.intellij.idea:idea:VERSION`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <groupId>com.jetbrains.intellij.idea</groupId>
   <artifactId>idea</artifactId>
   <version>2026.2.2</version>
   <packaging>zip</packaging>
</project>
```

so IDE can access them out-of-the-box when working with non-installers (`useInstaller=false`) IntelliJ Platform dependencies, while installers get fake coordinates like `idea:idealU:aarch64:VERSION`.

<img width="1203" height="602" alt="Image" src="https://github.com/user-attachments/assets/db0d8efd-ad40-4c20-815c-e71cd604c319" />

Eventually, Plugin DevKit resolves original sources for all the installers and non-IJ non-installers that don't have such sources present.
This is async process, and may result in you being confused that nothing's happening.

I may have an idea on how to make that better, still on the IntelliJ Platform Gradle Plugin side — prepare an Ivy artifact definition that points to sources a bit earlier, but I can't promise anything at this point.

**Comment by chylex** [comment]
I don't think the download begins automatically in the background when "Advanced Settings - Build Tools. Gradle - Download sources" is checked, right? If it did, then it wouldn't matter how long it takes, by the time I need to view IJ sources they should be downloaded and associated in the background, and I should never see decompiled sources.

The biggest UI issue is that *at the moment when I need sources*, usually when using "Go to Declaration" or "Find Usages" or clicking a debugger frame, the sources are not there. And then the "Download IntelliJ Platform Sources" action loses the target method or line I was trying to navigate to. So not only does it interrupt my focus during development or debugging, but after waiting for sources to get resolved, I have to *redo my previous action* to actually navigate to the correct place in the downloaded sources.

**Comment by chylex** [comment]
Another big issue (which I've either reported or starred years ago in YT) is that the decompiled sources editor notification is unclear about the reason sources are not attached. This is a more general problem with Gradle ever since IDEA stopped downloading dependency sources automatically, but the gist is that when downloading sources fails, there is no UI feedback whatsoever, no information to help diagnose the issue.

With plugin development, this also applies to "Download IntelliJ Platform Sources" when developing for modules and bundled plugins from IDEA Ultimate, or non-open IDEs like Rider, which don't have any sources at all - but the "Download IntelliJ Platform Sources" action still appears, and clicking it does nothing.

**Comment by chylex** [comment]
Went to work on https://github.com/chylex/IntelliJ-Inspection-Lens:

1. Opened the project.
2. Committed https://github.com/chylex/IntelliJ-Inspection-Lens/commit/08de8a1e5b08d18436265a2fe57ec384a17aa43b.
3. Used "Go to Declaration" on the newly added `com.intellij.diagnostic.JetBrainsMarketplaceErrorReportSubmitter` in `plugin.xml`.
4. Saw decompiled sources. Clicked "Download IntelliJ Platform Sources", waited, nothing happened.
5. Clicked "Sync All Gradle Projects", nothing happened.
6. Clicked "Download Sources" under Gradle, nothing happened.
7. Closed the decompiled sources and used "Go to Declaration" again, saw decompiled sources.
8. Clicked "Download IntelliJ Platform Sources" again, finally it resolved.

<img width="1715" height="555" alt="Image" src="https://github.com/user-attachments/assets/074c29d7-815e-44aa-8526-078fb88b1081" />

By step 7, I wasn't sure if there even were sources for this file, but I continued and after *all of that* it finally worked.
