### ISSUE TITLE
Gradle 8.11-rc-1: buildPlugin hangs on GitHub Actions

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/intellij-platform-gradle-plugin#1809]
### What happened?

When using Gradle 8.11-rc-1, the task `buildPlugin` hangs when running on GitHub Actions with the default linux runner. The bug does not occur on my local machine (macOS, MacBook Air M3 with 24 GB) nor in GitHub Codespaces.

This bug might be caused by Gradle, but it only occurs with this plugin.

### Relevant log output or stack trace

```shell
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$$Lambda/0x00007fb03c3ee7e0@2be71cf7.
org.gradle.api.UncheckedIOException: Could not add entry '/home/runner/.gradle/caches/8.11-rc-1/transforms/16a24b2b96496cc6bfd00ef589467c5b-f28c0740-7c31-4de4-8b7e-28b023a754ec/transformed/android-studio-2024.1.2.10-linux/android-studio/jbr/bin/jdeprscan' to cache fileHashes.bin (/home/runner/.gradle/caches/8.11-rc-1/fileHashes/fileHashes.bin).
	at org.gradle.cache.internal.btree.BTreePersistentIndexedCache.put(BTreePersistentIndexedCache.java:162)
	at org.gradle.cache.internal.DefaultMultiProcessSafeIndexedCache.lambda$put$1(DefaultMultiProcessSafeIndexedCache.java:67)
```

### Steps to reproduce

https://github.com/hfhbd/kobol/pull/771

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.11-rc-1

### Operating System

Linux

### Link to build, i.e. failing GitHub Action job

https://github.com/hfhbd/kobol/actions/runs/11446075260/job/31844484371?pr=771

**Comment by hfhbd** [comment]
Caused by: `No space left on device` because the old cache created with 8.10 will not be reused with Gradle 8.11 and my project itself is too big for the GitHub standard runners, so I have to the Gradle build cache.
And locally, I have enough free space.
