### ISSUE TITLE
Ide Tests fails with 'com.intellij.platform.instanceContainer.InstanceNotRegisteredException: com.intellij.platform.settings.SettingsController' after updating to 2.1.0

### ISSUE THREAD

**Issue by sbouchet** [JetBrains/intellij-platform-gradle-plugin#1834]
### What happened?

Our Integration test suite starts to fails after updating to 2.1.0. 
the tests overrides BasePlatformTestCase and its fails into the setUp() pahse, while initializingthe fixture.
everything runs fine with no change using 2.0.1

### Relevant log output or stack trace

```shell
com.intellij.platform.instanceContainer.InstanceNotRegisteredException: com.intellij.platform.settings.SettingsController
        at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:65)
        at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:699)
        at com.intellij.platform.ide.bootstrap.ApplicationLoader$initConfigurationStore$2$1.invokeSuspend(ApplicationLoader.kt:586)
        at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:42)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$task$1.invokeSuspend(testApplication.kt:172)
        at com.intellij.testFramework.common.TestApplicationKt$loadAppInUnitTestMode$3.invokeSuspend(testApplication.kt:182)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2$taskJob$1.invokeSuspend(PlatformTaskSupport.kt:216)

        Caused by:
        com.intellij.platform.instanceContainer.InstanceNotRegisteredException: com.intellij.platform.settings.SettingsController
            at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:65)
            at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:699)
            at com.intellij.platform.ide.bootstrap.ApplicationLoader$initConfigurationStore$2$1.invokeSuspend(ApplicationLoader.kt:586)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

### Steps to reproduce

checkout https://github.com/redhat-developer/intellij-openshift-connector, update gradle intelij plugin to 2.1.0 in libs.toml and run ./gradlew integrationTest. see the failures messages
whereas when no changes,  there is expected failures due to missing kubernetes cluster ( kind ) , but ToolFactoryTest for example is fine

### Gradle IntelliJ Plugin version

2.1.0

### Gradle version

8.5

### Operating System

Linux

### Link to build, i.e. failing GitHub Action job

https://github.com/redhat-developer/intellij-openshift-connector/actions/runs/12164905013/job/33928092232?pr=948

**Comment by hsz** [comment]
Hey, Stephane!
I see you're introducing a custom source set for your instrumentation tests. Unfortunately, this approach hasn't been properly tested yet.

Looking at the `test` module's dependencies, the `idea:ideaIC:aarch64:2024.3` dependency is present.
We can see a listing of all required jars to run IDE or tests in its details.

<img width="1427" alt="image" src="https://github.com/user-attachments/assets/bf1622db-6ce7-4f63-9a31-a4fba09b6bc6">

However, for the `it` module, `ideaIC` is absent. This may be because the IntelliJ Platform dependency is resolved from the Internet, i.e., the DMG archive (on macOS), and still requires dependency transformation to be executed—like extracting the archive and collecting relevant jars.

For the `compileClasspath`/`runtimeClasspath`/`test*` configurations, the IntelliJ Platform Gradle Plugin adds special attributes that instruct Gradle to take care of those custom archives properly:

https://github.com/JetBrains/intellij-platform-gradle-plugin/blob/5a33c4f906cacce27d58e6b27a82ba26b7f8e425/src/main/kotlin/org/jetbrains/intellij/platform/gradle/plugins/project/IntelliJPlatformBasePlugin.kt#L347-L358

They're most likely missing, and you include a raw DMG archive for the `it` classpath.

**Comment by sbouchet** [comment]
For info, same error with latest 2.2.0

**Comment by sbouchet** [comment]
what can i see for now is different. however, the scope is different ( from provided to runtime). is there a task i can use to print the classpath and scope for better understanding/diff ?

**Comment by hsz** [comment]
To inspect the classpath used by the `test` task, you can:

```kotlin
tasks{
    test {
        doFirst {
            println("classpath = \n${classpath.joinToString("\n")}")
        }
    }
}
```

**Comment by sbouchet** [comment]
With your above task, i can spot that the custom `integrationtest` classpath is missing a lot of IJ modules, compared to the simple `test`. i suppose this is likely why it's failling... 
![image](https://github.com/user-attachments/assets/ac9946f6-02bc-44ec-8973-18bc273b3cbd)

**Comment by vbmacher** [comment]
Hi all, I had similar issue with my plugin https://github.com/vbmacher/intellij-cucumber-scala - tests throwing 

```
[info] - testLineMarker *** FAILED ***
[info]   com.intellij.platform.instanceContainer.InstanceNotRegisteredException: com.intellij.platform.settings.SettingsController
[info]   at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:65)
[info]   at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:699)
...
```

After several months I resolved it just with updating sbt-idea-plugin from version 3.20.1 to 3.26.2 (they don't even show the latest version in releases).

Just saying it's maybe worth checking what has changed between these versions and check if the same kind of changes shouldnt be applied in the gradle plugin (or first maybe try to update it).

**Comment by sbouchet** [comment]
Hi,
my current workaround was to revert to test against 2024.1 and not 2024.3.
maybe it's due to changes in ProjectActivity changes / indexing changes  in 2024.2+ https://plugins.jetbrains.com/docs/intellij/testing-faq.html#how-to-handle-projectactivity
