### ISSUE TITLE
java.lang.Throwable: 'ai.installer.notification.group.name' is not found with v2.2.0 and IntelliJ 2024.3.1 

### ISSUE THREAD

**Issue by thetric** [JetBrains/intellij-platform-gradle-plugin#1838]
### What happened?

When updating the IntelliJ version in the build.gradle.kts from 2024.3 to 2024.3.1, my tests started failing with the following error. Not sure if this is a bug in the IntelliJ platform tho

### Relevant log output or stack trace

```shell
ERROR: 'ai.installer.notification.group.name' is not found (baseBundleName=messages.LLMInstallerBundle, bundle=com.intellij.IntelliJResourceBundle@218fbbb9)
java.lang.Throwable: 'ai.installer.notification.group.name' is not found (baseBundleName=messages.LLMInstallerBundle, bundle=com.intellij.IntelliJResourceBundle@218fbbb9)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.BundleBaseKt.useDefaultValue(BundleBase.kt:283)
	at com.intellij.IntelliJResourceBundle.getMessage(IntelliJResourceBundle.kt:38)
	at com.intellij.BundleBaseKt.messageOrDefault(BundleBase.kt:246)
	at com.intellij.BundleBase.messageOrDefault(BundleBase.kt:105)
	at com.intellij.notification.impl.NotificationGroupEP.getDisplayName(NotificationGroupEP.java:118)
	at com.intellij.notification.impl.NotificationGroupManagerImplKt.registerNotificationGroup(NotificationGroupManagerImpl.kt:88)
	at com.intellij.notification.impl.NotificationGroupManagerImplKt.computeGroups$lambda$0(NotificationGroupManagerImpl.kt:67)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.kt:1087)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.kt:143)
	at com.intellij.notification.impl.NotificationGroupManagerImplKt.computeGroups(NotificationGroupManagerImpl.kt:66)
...
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:751)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:695)
	at com.intellij.notification.NotificationGroupManager.getInstance(NotificationGroupManager.java:19)
	at com.example.DummyTest.test(DummyTest.java:9)
...
	at junit.framework.TestCase.runTest(TestCase.java:177)
...
```

### Steps to reproduce

Repro:
[Archive.zip](https://github.com/user-attachments/files/18081189/Archive.zip)

```kotlin
import org.jetbrains.intellij.platform.gradle.IntelliJPlatformType
import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.intellij.platform.gradle.models.ProductRelease

plugins {
    id("java")
    id("org.jetbrains.intellij.platform") version "2.2.0"
}

group = "com.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    testImplementation("junit:junit:4.13.2")

    intellijPlatform {
        // 👇 change this to 2024.3 to make the test work
        intellijIdeaCommunity("2024.3.1")
        bundledPlugins(listOf("com.intellij.properties", "com.intellij.java", "com.intellij.modules.json"))
        testFramework(TestFrameworkType.Platform)
        pluginVerifier()
    }
}

val minIntelliJVersion = "243"
val maxIntelliJVersion = "243.*"

intellijPlatform {
    pluginVerification {
        ides {
            recommended()
            select {
                types = listOf(IntelliJPlatformType.IntellijIdeaCommunity)
                channels = listOf(ProductRelease.Channel.RELEASE)
                sinceBuild = minIntelliJVersion
                untilBuild = maxIntelliJVersion
            }
        }
    }
    buildSearchableOptions = false
}
```

```xml
<!-- src/main/resources/META-INF/plugin.xml -->
<idea-plugin>
    <id>com.example</id>
    <name>Test</name>
    <vendor email="shepard@normandy.alliance" url="https://example.com/">test</vendor>
    <depends>com.intellij.modules.platform</depends>

    <extensions defaultExtensionNs="com.intellij">
        <notificationGroup displayType="BALLOON" id="MyNotificationTest" isLogByDefault="true"/>
    </extensions>
</idea-plugin>
```

```java
// src/test/java/com/example/DummyTest.java
package com.example;

import com.intellij.notification.NotificationGroupManager;
import com.intellij.notification.NotificationType;
import com.intellij.testFramework.fixtures.BasePlatformTestCase;

public class DummyTest extends BasePlatformTestCase {
    public void test() {
        NotificationGroupManager.getInstance().getNotificationGroup("MyNotificationTest")
                                .createNotification("MyNotificationTest", NotificationType.ERROR)
                                .notify(myFixture.getProject());
    }
}
```
- Gradle: 8.11.1
- IntelliJ Platform Gradle Plugin: 2.2.0
- Java 21.0.5, BellSoft Liberica 21.0.5 - aarch64 (Mac)
- OS: Mac OS 15.1.1 (24B91)

### Gradle IntelliJ Plugin version

2.2.0

### Gradle version

8.11.1

### Operating System

macOS

**Comment by YannCebron** [comment]
Thanks for reporting, this looks like an issue with the 2024.3.1 release, please rollback to 2024.3.0 in the meantime

**Comment by marat-rkh** [comment]
@thetric did you close it intentionally? Because we actually need to fix that, so I would keep it open.

**Comment by thetric** [comment]
Ah, sorry. I misunderstood the comment from YannCebron 

> Thanks for reporting, this looks like an issue with the 2024.3.1 release [...]😅

**Comment by halirutan** [comment]
It's OK to keep this issue open. It needs fixing in the platform, but we'll close it once the underlying deficiency has been corrected and things work again.

**Comment by PrzemyslawSwiderski** [comment]
Adding `intellij.platform.ijent.impl` to a `bundledPlugins` fixed this issue in my case.

**Comment by thetric** [comment]
Seems to be fixed in IntelliJ 2024.3.2.1
