### ISSUE TITLE
CollectorTransformer execution failed with Plugin 2.2.x for the Grazie Pro plugin

### ISSUE THREAD

**Issue by ahus1** [JetBrains/intellij-platform-gradle-plugin#1851]
### What happened?

I want to upgrade from plugin version 2.1.0 to 2.2.x, and now the build fails with a compile error most likely due to the transformer failure.

Updating the Grazie professional plugin to `com.intellij.grazie.pro:0.3.354` doesn't help, it is the same error message. 

What makes it difficult to fix/reproduce: The exception of the transformer happens only on the first run, as the transformed output is kept. On the next run, it fails with only the compile error as the classes from the Grazie plugin are not available in the compile class path. The same exception occurs only if I clean the gradle caches. 

### Relevant log output or stack trace

```shell
[org.jetbrains.intellij.platform] org.jetbrains.intellij.platform.gradle.artifacts.transform.CollectorTransformer$Inject1 execution failed.
org.gradle.api.GradleException: Unknown input: /home/aschwart/.gradle/caches/transforms-4/c4bbb37430a2fc123dc9a2c3426f631b/transformed/com.intellij.grazie.pro-0.3.354
        at org.jetbrains.intellij.platform.gradle.artifacts.transform.CollectorTransformer.transform(CollectorTransformer.kt:103)
        at org.gradle.api.internal.artifacts.transform.DefaultTransform.transform(DefaultTransform.java:276)
        at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution$2.call(AbstractTransformExecution.java:143)
        at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution$2.call(AbstractTransformExecution.java:137)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution.executeWithinTransformerListener(AbstractTransformExecution.java:137)
        at org.gradle.api.internal.artifacts.transform.AbstractTransformExecution.execute(AbstractTransformExecution.java:130)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
```

### Steps to reproduce

See PR https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/1777

Run `./gradlew check` 

### Gradle IntelliJ Plugin version

2.2.1, 2.2.2-SNAPSHOT

### Gradle version

8.7, 8.10.2

### Operating System

Linux, Windows

### Link to build, i.e. failing GitHub Action job

https://github.com/asciidoctor/asciidoctor-intellij-plugin/actions/runs/13215388662/job/36894039608?pr=1777

[logs_34115014782.zip](https://github.com/user-attachments/files/18718568/logs_34115014782.zip)

**Comment by ahus1** [comment]
The problems persists. I tried a different OS, a new Gradle version, and the SNAPSHOT version of the plugin. Nothing helps here. 

I assume I need the new plugin version to successfully build the EAP 2025 version? Please help!

**Comment by hsz** [comment]
@ahus1 thanks for bumping that. The `CollectorTransformer` fails to load the Grazie Pro plugin due to issues found by the Plugin Verifier:

```
Could not resolve plugin: '/Users/hsz/.gradle/caches/8.11.1/transforms/ddcadb78e425bf57dd5d6c7941707f4d/transformed/com.intellij.grazie.pro-0.3.359/grazie-pro':
Invalid plugin descriptor 'plugin.xml'. The plugin ID 'com.intellij.grazie.pro' has a prefix 'com.intellij' that is not allowed.
Invalid plugin descriptor 'plugin.xml'. The plugin ID 'com.intellij.grazie.pro' should not include the word 'intellij'.
Invalid plugin descriptor 'plugin.xml'. The <release-version> parameter (03) format is invalid. Ensure it is an integer with at least two digits.
```

@novotnyr could you please take a look at it?

**Comment by el7cosmos** [comment]
I have a similar problem for other plugin, it failed to load `fr.adrienbrault.idea.symfony2plugin`
